# Generated by Django 5.2.5 on 2025-09-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='student',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='school.subject'),
        ),
    ]
