# Generated by Django 5.2.5 on 2025-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_quizanswer_marks_remove_quizanswer_quiz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCreateUpdateSerializer',
        ),
    ]
